### ISSUE TITLE
Elicitação de requisitos

### ISSUE THREAD

**Issue by damarcones** [PI2-Grupo-04/Aplicativo#24]
Fazer um parágrafo na seção "Elicitação de requisitos" no relatório explicando os seguintes documentos:

- [x] NFR - Damarcones
- [x] First things first - Samuel
- [x] MoSCoW - Damarcones
- [x] Especificação suplementar - Letícia

**Comment by brunaalmeidasantos** [comment]
Elicitação de requisitos documentado no relatório.
