### ISSUE TITLE
Diagrama entidade-relacionamento

### ISSUE THREAD

**Issue by brunaalmeidasantos** [PI2-Grupo-04/Aplicativo#38]
Criar diagrama entidade-relacionamento e:

- [x] Adicionar ao repositório;
- [x] Adicionar ao relatório, na seção de modelagem.

Exemplo: https://damarcones.github.io/Gama_Boyle_Lab/diagramas/diagrama-entidade/

**Comment by leticiaarj** [comment]
@brunaalmeidasantos, por favor corrigir para envio à comissão de Qualidade.

**Comment by brunaalmeidasantos** [comment]
@leticiaarj diagrama de acordo com o esperado, colocar apenas uma legenda para identificar a figura.

**Comment by brunaalmeidasantos** [comment]
Diagrama feito pela @leticiaarj  e já colocado no relatório.
