### ISSUE TITLE
Diagrama de arquitetura funcional

### ISSUE THREAD

**Issue by brunaalmeidasantos** [PI2-Grupo-04/Aplicativo#40]
Criar diagrama de arquitetura funcional e:

- [x] Adicionar ao repositório;
- [x] Adicionar ao relatório, na seção de modelagem.

Exemplo: https://damarcones.github.io/Gama_Boyle_Lab/diagramas/diagrama-arquitetura-funcional/

**Comment by leticiaarj** [comment]
@brunaalmeidasantos, por favor corrigir para enviar para a Comissão de Qualidade.

**Comment by brunaalmeidasantos** [comment]
@leticiaarj diagrama de acordo com o esperado, colocar apenas uma legenda para identificar a figura.

**Comment by brunaalmeidasantos** [comment]
Diagrama feito pela @leticiaarj e já adicionado ao relatório.
