### ISSUE TITLE
Estruturação do banco de dados

### ISSUE THREAD

**Issue by brunaalmeidasantos** [PI2-Grupo-04/Aplicativo#59]
Estruturação do banco de dados MongoDB

**Comment by sammyzord** [comment]
Código necessário para a conexão com o banco de dados de desenvolvimento foram adicionados, agora só falta a criação das models

**Comment by brunaalmeidasantos** [comment]
Tarefa finalizada. Outras configurações do banco de dados serão implementadas para o PC3.
