### ISSUE TITLE
Códigos para integração

### ISSUE THREAD

**Issue by brunaalmeidasantos** [PI2-Grupo-04/Aplicativo#60]
Pesquisar e implementar alguns códigos que serão utilizados para integração com automação.
Quando encontrar algum código que poderá ser útil para o projeto, favor comentar aqui na issue sobre o que se trata o código.

**Comment by damarcones** [comment]
Os códigos para o PC2 foram feitos junto com a equipe de automação e para o PC3 existirão mais códigos.
